### ISSUE TITLE
AngularJs vs Angular 4

### ISSUE THREAD

**Issue by RodolpheGohard** [mobapi/docker-nginx-angular-env#1]
Hello, nice work, this is pretty much what I was looking for, except I'm on an angular stack not angularJS.

Thanks to angular naming havoc, I suggest mentionning explicitly in the README that the target framework is angular**.js**

**Comment by fluciotto** [comment]
Hi,

Thanks for your comment!
You're right about the output file documentation, i'll update it soon.
